// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const backfillProjectURL = `-- name: BackfillProjectURL :exec
?;

UPDATE project SET url = ? WHERE id = ? AND url IS NU
`

type BackfillProjectURLParams struct {
	Url sql.NullString
	ID  int64
}

func (q *Queries) BackfillProjectURL(ctx context.Context, arg BackfillProjectURLParams) error {
	_, err := q.db.ExecContext(ctx, backfillProjectURL, arg.Url, arg.ID)
	return err
}

const bugCitersOfInv = `-- name: BugCitersOfInv :many
Y t.ord;

SELECT b.ord FROM bug_fix j JOIN bug b ON b.id = j.bug_id WHERE j.inv_id = ? ORDER
`

func (q *Queries) BugCitersOfInv(ctx context.Context, invID int64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, bugCitersOfInv, invID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var ord sql.NullInt64
		if err := rows.Scan(&ord); err != nil {
			return nil, err
		}
		items = append(items, ord)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bugFixInvOrds = `-- name: BugFixInvOrds :many
Y t.ord;


SELECT i.ord FROM bug_fix j JOIN invariant i ON i.id = j.inv_id WHERE j.bug_id = ? ORDER
`

// ============================================================ reads: cite resolution (export.go / next.go)
func (q *Queries) BugFixInvOrds(ctx context.Context, bugID int64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, bugFixInvOrds, bugID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var ord sql.NullInt64
		if err := rows.Scan(&ord); err != nil {
			return nil, err
		}
		items = append(items, ord)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bugsByProject = `-- name: BugsByProject :many
BY ord;

SELECT id, ord, date, cause FROM bug WHERE project_id = ? ORDE
`

type BugsByProjectRow struct {
	ID    int64
	Ord   sql.NullInt64
	Date  string
	Cause string
}

func (q *Queries) BugsByProject(ctx context.Context, projectID sql.NullInt64) ([]BugsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, bugsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BugsByProjectRow{}
	for rows.Next() {
		var i BugsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Ord,
			&i.Date,
			&i.Cause,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const citersOfIface = `-- name: CitersOfIface :many
ord = ?;


SELECT t.ord FROM task_cites_iface j JOIN task t ON t.id = j.task_id WHERE j.iface_id = ? ORDER
`

// ============================================================ reads: refs (refs.go)
func (q *Queries) CitersOfIface(ctx context.Context, ifaceID int64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, citersOfIface, ifaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var ord sql.NullInt64
		if err := rows.Scan(&ord); err != nil {
			return nil, err
		}
		items = append(items, ord)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const constraintsByFeature = `-- name: ConstraintsByFeature :many
R BY id;

SELECT text FROM "constraint" WHERE feature_id = ? ORD
`

func (q *Queries) ConstraintsByFeature(ctx context.Context, featureID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, constraintsByFeature, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var text string
		if err := rows.Scan(&text); err != nil {
			return nil, err
		}
		items = append(items, text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProject = `-- name: CreateProject :execlastid
L;

INSERT INTO project(url, path) VALUES(?
`

type CreateProjectParams struct {
	Url  sql.NullString
	Path string
}

// url is the nullable column, so sqlc types this param sql.NullString — pass an
// unset NullString for a project first seen without an origin.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProject, arg.Url, arg.Path)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteProjectBugs = `-- name: DeleteProjectBugs :exec
_id = ?;

DELETE FROM bug WHERE projec
`

func (q *Queries) DeleteProjectBugs(ctx context.Context, projectID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectBugs, projectID)
	return err
}

const deleteProjectFeatures = `-- name: DeleteProjectFeatures :exec
R) AS n;

DELETE FROM feature WHERE projec
`

func (q *Queries) DeleteProjectFeatures(ctx context.Context, projectID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectFeatures, projectID)
	return err
}

const deleteProjectInterfaces = `-- name: DeleteProjectInterfaces :exec
_id = ?;

DELETE FROM interface WHERE projec
`

func (q *Queries) DeleteProjectInterfaces(ctx context.Context, projectID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectInterfaces, projectID)
	return err
}

const deleteProjectInvariants = `-- name: DeleteProjectInvariants :exec
_id = ?;

DELETE FROM invariant WHERE projec
`

func (q *Queries) DeleteProjectInvariants(ctx context.Context, projectID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectInvariants, projectID)
	return err
}

const deleteProjectResearch = `-- name: DeleteProjectResearch :exec
_id = ?;

DELETE FROM research WHERE projec
`

func (q *Queries) DeleteProjectResearch(ctx context.Context, projectID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectResearch, projectID)
	return err
}

const deprecateInterface = `-- name: DeprecateInterface :execrows
= ?;

UPDATE interface SET status = 'deprecated' WHERE project_id = ? AND name
`

type DeprecateInterfaceParams struct {
	ProjectID sql.NullInt64
	Name      string
}

func (q *Queries) DeprecateInterface(ctx context.Context, arg DeprecateInterfaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deprecateInterface, arg.ProjectID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deprecatedCiteWarnings = `-- name: DeprecatedCiteWarnings :many
R) AS n;

SELECT t.ord, i.name
FROM task_cites_iface j
JOIN interface i ON i.id = j.iface_id
JOIN task t ON t.id = j.task_id
JOIN feature f ON f.id = t.feature_id
WHERE f.project_id = ? AND i.status = 'deprecated'
ORDER BY t.ord
`

type DeprecatedCiteWarningsRow struct {
	Ord  sql.NullInt64
	Name string
}

func (q *Queries) DeprecatedCiteWarnings(ctx context.Context, projectID sql.NullInt64) ([]DeprecatedCiteWarningsRow, error) {
	rows, err := q.db.QueryContext(ctx, deprecatedCiteWarnings, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeprecatedCiteWarningsRow{}
	for rows.Next() {
		var i DeprecatedCiteWarningsRow
		if err := rows.Scan(&i.Ord, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const editBug = `-- name: EditBug :execrows
= ?;

UPDATE bug SET cause = ? WHERE project_id = ? AND ord
`

type EditBugParams struct {
	Cause     string
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
}

func (q *Queries) EditBug(ctx context.Context, arg EditBugParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, editBug, arg.Cause, arg.ProjectID, arg.Ord)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const editConstraint = `-- name: EditConstraint :execrows
= ?;

UPDATE "constraint" SET text = ? WHERE id
`

type EditConstraintParams struct {
	Text string
	ID   int64
}

func (q *Queries) EditConstraint(ctx context.Context, arg EditConstraintParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, editConstraint, arg.Text, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const editGoal = `-- name: EditGoal :execrows
= ?;

UPDATE goal SET text = ? WHERE id
`

type EditGoalParams struct {
	Text string
	ID   int64
}

func (q *Queries) EditGoal(ctx context.Context, arg EditGoalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, editGoal, arg.Text, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const editInterfaceSig = `-- name: EditInterfaceSig :execrows
?);

UPDATE interface SET sig = ? WHERE project_id = ? AND name
`

type EditInterfaceSigParams struct {
	Sig       string
	ProjectID sql.NullInt64
	Name      string
}

func (q *Queries) EditInterfaceSig(ctx context.Context, arg EditInterfaceSigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, editInterfaceSig, arg.Sig, arg.ProjectID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const editInvariant = `-- name: EditInvariant :execrows
_at;


UPDATE invariant SET text = ? WHERE project_id = ? AND ord
`

type EditInvariantParams struct {
	Text      string
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
}

// ============================================================ updates / deletes (return rows affected for the n==0 not-found check)
func (q *Queries) EditInvariant(ctx context.Context, arg EditInvariantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, editInvariant, arg.Text, arg.ProjectID, arg.Ord)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const editResearch = `-- name: EditResearch :execrows
= ?;

UPDATE research SET finding = ? WHERE project_id = ? AND ord
`

type EditResearchParams struct {
	Finding   string
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
}

func (q *Queries) EditResearch(ctx context.Context, arg EditResearchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, editResearch, arg.Finding, arg.ProjectID, arg.Ord)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const editTask = `-- name: EditTask :execrows
= ?;

UPDATE task SET text = ? WHERE task.ord = ? AND task.feature_id IN (SELECT feature.id FROM feature WHERE feature.project_id
`

type EditTaskParams struct {
	Text      string
	Ord       sql.NullInt64
	ProjectID sql.NullInt64
}

func (q *Queries) EditTask(ctx context.Context, arg EditTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, editTask, arg.Text, arg.Ord, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const featureGoalConstraintCount = `-- name: FeatureGoalConstraintCount :one
_id = ?;

SELECT CAST(
	(SELECT count(*) FROM goal WHERE goal.feature_id = ?)
	+ (SELECT count(*) FROM "constraint" WHERE "constraint".feature_id = ?)
AS INTEG
`

type FeatureGoalConstraintCountParams struct {
	FeatureID   int64
	FeatureID_2 int64
}

// Two positional params, both the same feature id (FeatureID, FeatureID_2).
func (q *Queries) FeatureGoalConstraintCount(ctx context.Context, arg FeatureGoalConstraintCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, featureGoalConstraintCount, arg.FeatureID, arg.FeatureID_2)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const featureOrdByID = `-- name: FeatureOrdByID :one
= ?;

SELECT ord FROM feature WHERE id
`

func (q *Queries) FeatureOrdByID(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, featureOrdByID, id)
	var ord sql.NullInt64
	err := row.Scan(&ord)
	return ord, err
}

const featurePK = `-- name: FeaturePK :one
?);

SELECT id FROM feature WHERE project_id = ? AND ord
`

type FeaturePKParams struct {
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
}

func (q *Queries) FeaturePK(ctx context.Context, arg FeaturePKParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, featurePK, arg.ProjectID, arg.Ord)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const featureStageCounts = `-- name: FeatureStageCounts :one
status;

SELECT
	CAST(count(*) AS INTEGER) AS total,
	CAST(COALESCE(SUM(CASE WHEN status = 'x' THEN 1 ELSE 0 END), 0) AS INTEGER) AS done,
	CAST(COALESCE(SUM(CASE WHEN status = '.' THEN 1 ELSE 0 END), 0) AS INTEGER) AS todo
FROM task WHERE featur
`

type FeatureStageCountsRow struct {
	Total int64
	Done  int64
	Todo  int64
}

func (q *Queries) FeatureStageCounts(ctx context.Context, featureID int64) (FeatureStageCountsRow, error) {
	row := q.db.QueryRowContext(ctx, featureStageCounts, featureID)
	var i FeatureStageCountsRow
	err := row.Scan(&i.Total, &i.Done, &i.Todo)
	return i, err
}

const featuresByProject = `-- name: FeaturesByProject :many
BY ord;

SELECT id, ord, name FROM feature WHERE project_id = ? ORDE
`

type FeaturesByProjectRow struct {
	ID   int64
	Ord  sql.NullInt64
	Name string
}

func (q *Queries) FeaturesByProject(ctx context.Context, projectID sql.NullInt64) ([]FeaturesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, featuresByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeaturesByProjectRow{}
	for rows.Next() {
		var i FeaturesByProjectRow
		if err := rows.Scan(&i.ID, &i.Ord, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gateVerdict = `-- name: GateVerdict :one
LIMIT 1;

SELECT verdict FROM gate WHERE featur
`

func (q *Queries) GateVerdict(ctx context.Context, featureID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, gateVerdict, featureID)
	var verdict string
	err := row.Scan(&verdict)
	return verdict, err
}

const goalsByFeature = `-- name: GoalsByFeature :many
BY ord;

SELECT text FROM goal WHERE feature_id = ? ORD
`

func (q *Queries) GoalsByFeature(ctx context.Context, featureID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, goalsByFeature, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var text string
		if err := rows.Scan(&text); err != nil {
			return nil, err
		}
		items = append(items, text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBug = `-- name: InsertBug :execlastid
?);

INSERT INTO bug(project_id, ord, date, cause) VALUES(?, ?, ?
`

type InsertBugParams struct {
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
	Date      string
	Cause     string
}

func (q *Queries) InsertBug(ctx context.Context, arg InsertBugParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertBug,
		arg.ProjectID,
		arg.Ord,
		arg.Date,
		arg.Cause,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertBugFix = `-- name: InsertBugFix :exec
?);

INSERT INTO bug_fix(bug_id, inv_id) VALUES(?
`

type InsertBugFixParams struct {
	BugID int64
	InvID int64
}

func (q *Queries) InsertBugFix(ctx context.Context, arg InsertBugFixParams) error {
	_, err := q.db.ExecContext(ctx, insertBugFix, arg.BugID, arg.InvID)
	return err
}

const insertConstraint = `-- name: InsertConstraint :exec
?);

INSERT INTO "constraint"(feature_id, text) VALUES(?
`

type InsertConstraintParams struct {
	FeatureID int64
	Text      string
}

func (q *Queries) InsertConstraint(ctx context.Context, arg InsertConstraintParams) error {
	_, err := q.db.ExecContext(ctx, insertConstraint, arg.FeatureID, arg.Text)
	return err
}

const insertFeature = `-- name: InsertFeature :execlastid
= ?;


INSERT INTO feature(project_id, ord, name) VALUES(?, ?
`

type InsertFeatureParams struct {
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
	Name      string
}

// ============================================================ inserts (mutations.go / edit.go / import.go)
func (q *Queries) InsertFeature(ctx context.Context, arg InsertFeatureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertFeature, arg.ProjectID, arg.Ord, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertGoal = `-- name: InsertGoal :exec
= ?;

INSERT INTO goal(feature_id, text) VALUES(?
`

type InsertGoalParams struct {
	FeatureID int64
	Text      string
}

func (q *Queries) InsertGoal(ctx context.Context, arg InsertGoalParams) error {
	_, err := q.db.ExecContext(ctx, insertGoal, arg.FeatureID, arg.Text)
	return err
}

const insertInterface = `-- name: InsertInterface :execlastid
?);

INSERT INTO interface(project_id, kind, name, sig) VALUES(?, ?, ?
`

type InsertInterfaceParams struct {
	ProjectID sql.NullInt64
	Kind      string
	Name      string
	Sig       string
}

func (q *Queries) InsertInterface(ctx context.Context, arg InsertInterfaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertInterface,
		arg.ProjectID,
		arg.Kind,
		arg.Name,
		arg.Sig,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertInvariant = `-- name: InsertInvariant :exec
?);

INSERT INTO invariant(project_id, ord, text) VALUES(?, ?
`

type InsertInvariantParams struct {
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
	Text      string
}

func (q *Queries) InsertInvariant(ctx context.Context, arg InsertInvariantParams) error {
	_, err := q.db.ExecContext(ctx, insertInvariant, arg.ProjectID, arg.Ord, arg.Text)
	return err
}

const insertResearch = `-- name: InsertResearch :exec
?);

INSERT INTO research(project_id, ord, topic, finding, src) VALUES(?, ?, ?, ?
`

type InsertResearchParams struct {
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
	Topic     string
	Finding   string
	Src       string
}

func (q *Queries) InsertResearch(ctx context.Context, arg InsertResearchParams) error {
	_, err := q.db.ExecContext(ctx, insertResearch,
		arg.ProjectID,
		arg.Ord,
		arg.Topic,
		arg.Finding,
		arg.Src,
	)
	return err
}

const insertTask = `-- name: InsertTask :execlastid
?);

INSERT INTO task(feature_id, ord, text) VALUES(?, ?
`

type InsertTaskParams struct {
	FeatureID int64
	Ord       sql.NullInt64
	Text      string
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertTask, arg.FeatureID, arg.Ord, arg.Text)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertTaskCiteIface = `-- name: InsertTaskCiteIface :exec
?);

INSERT INTO task_cites_iface(task_id, iface_id) VALUES(?
`

type InsertTaskCiteIfaceParams struct {
	TaskID  int64
	IfaceID int64
}

func (q *Queries) InsertTaskCiteIface(ctx context.Context, arg InsertTaskCiteIfaceParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskCiteIface, arg.TaskID, arg.IfaceID)
	return err
}

const insertTaskCiteInv = `-- name: InsertTaskCiteInv :exec
?);

INSERT INTO task_cites_inv(task_id, inv_id) VALUES(?
`

type InsertTaskCiteInvParams struct {
	TaskID int64
	InvID  int64
}

func (q *Queries) InsertTaskCiteInv(ctx context.Context, arg InsertTaskCiteInvParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskCiteInv, arg.TaskID, arg.InvID)
	return err
}

const insertTaskFull = `-- name: InsertTaskFull :execlastid
?);

INSERT INTO task(feature_id, ord, text, status) VALUES(?, ?, ?
`

type InsertTaskFullParams struct {
	FeatureID int64
	Ord       sql.NullInt64
	Text      string
	Status    string
}

func (q *Queries) InsertTaskFull(ctx context.Context, arg InsertTaskFullParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertTaskFull,
		arg.FeatureID,
		arg.Ord,
		arg.Text,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertTest = `-- name: InsertTest :exec
?);

INSERT INTO test(invariant_id, name) VALUES(?, ?)
ON CONFLICT(invariant_id, name) DO NOT
`

type InsertTestParams struct {
	InvariantID int64
	Name        string
}

func (q *Queries) InsertTest(ctx context.Context, arg InsertTestParams) error {
	_, err := q.db.ExecContext(ctx, insertTest, arg.InvariantID, arg.Name)
	return err
}

const insertUnknown = `-- name: InsertUnknown :exec
= ?;

INSERT INTO unknown(feature_id, ord, text) VALUES(?, ?
`

type InsertUnknownParams struct {
	FeatureID int64
	Ord       sql.NullInt64
	Text      string
}

func (q *Queries) InsertUnknown(ctx context.Context, arg InsertUnknownParams) error {
	_, err := q.db.ExecContext(ctx, insertUnknown, arg.FeatureID, arg.Ord, arg.Text)
	return err
}

const interfaceIDByName = `-- name: InterfaceIDByName :one
= ?;

SELECT id FROM interface WHERE project_id = ? AND name
`

type InterfaceIDByNameParams struct {
	ProjectID sql.NullInt64
	Name      string
}

func (q *Queries) InterfaceIDByName(ctx context.Context, arg InterfaceIDByNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, interfaceIDByName, arg.ProjectID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const interfacesByProject = `-- name: InterfacesByProject :many
_id = ?;


SELECT kind, name, sig, status FROM interface WHERE project_id = ? ORD
`

type InterfacesByProjectRow struct {
	Kind   string
	Name   string
	Sig    string
	Status string
}

// ============================================================ reads: canonical row lists (export.go + list.go share these, V18)
func (q *Queries) InterfacesByProject(ctx context.Context, projectID sql.NullInt64) ([]InterfacesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, interfacesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InterfacesByProjectRow{}
	for rows.Next() {
		var i InterfacesByProjectRow
		if err := rows.Scan(
			&i.Kind,
			&i.Name,
			&i.Sig,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invariantIDByOrd = `-- name: InvariantIDByOrd :one
?);

SELECT id FROM invariant WHERE project_id = ? AND ord
`

type InvariantIDByOrdParams struct {
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
}

func (q *Queries) InvariantIDByOrd(ctx context.Context, arg InvariantIDByOrdParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, invariantIDByOrd, arg.ProjectID, arg.Ord)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const invariantsByProject = `-- name: InvariantsByProject :many
BY ord;

SELECT ord, text FROM invariant WHERE project_id = ? ORDE
`

type InvariantsByProjectRow struct {
	Ord  sql.NullInt64
	Text string
}

func (q *Queries) InvariantsByProject(ctx context.Context, projectID sql.NullInt64) ([]InvariantsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, invariantsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvariantsByProjectRow{}
	for rows.Next() {
		var i InvariantsByProjectRow
		if err := rows.Scan(&i.Ord, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextActionableTask = `-- name: NextActionableTask :one
Y f.ord;

SELECT f.ord AS feat_ord, f.name AS feat_name, f.id AS feat_id,
       t.ord AS task_ord, t.status, t.text, t.id AS task_id
FROM task t JOIN feature f ON f.id = t.feature_id
WHERE f.project_id = ? AND t.status != 'x'
ORDER BY f.ord ASC,
	CASE t.status WHEN '~' THEN 0 ELSE 1 END ASC,
	t.ord ASC
`

type NextActionableTaskRow struct {
	FeatOrd  sql.NullInt64
	FeatName string
	FeatID   int64
	TaskOrd  sql.NullInt64
	Status   string
	Text     string
	TaskID   int64
}

func (q *Queries) NextActionableTask(ctx context.Context, projectID sql.NullInt64) (NextActionableTaskRow, error) {
	row := q.db.QueryRowContext(ctx, nextActionableTask, projectID)
	var i NextActionableTaskRow
	err := row.Scan(
		&i.FeatOrd,
		&i.FeatName,
		&i.FeatID,
		&i.TaskOrd,
		&i.Status,
		&i.Text,
		&i.TaskID,
	)
	return i, err
}

const nextBugOrd = `-- name: NextBugOrd :one
= ?;

SELECT CAST(COALESCE(MAX(ord), 0) + 1 AS INTEGER) AS next_ord FROM bug WHERE project_id
`

func (q *Queries) NextBugOrd(ctx context.Context, projectID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextBugOrd, projectID)
	var next_ord int64
	err := row.Scan(&next_ord)
	return next_ord, err
}

const nextFeatureOrd = `-- name: NextFeatureOrd :one
= ?;

SELECT CAST(COALESCE(MAX(ord), 0) + 1 AS INTEGER) AS next_ord FROM feature WHERE project_id
`

func (q *Queries) NextFeatureOrd(ctx context.Context, projectID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextFeatureOrd, projectID)
	var next_ord int64
	err := row.Scan(&next_ord)
	return next_ord, err
}

const nextInvariantOrd = `-- name: NextInvariantOrd :one
?);


SELECT CAST(COALESCE(MAX(ord), 0) + 1 AS INTEGER) AS next_ord FROM invariant WHERE project_id
`

// ============================================================ ordinals (V26)
// COALESCE(MAX(ord),0)+1, cast so sqlc yields a clean int64.
func (q *Queries) NextInvariantOrd(ctx context.Context, projectID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextInvariantOrd, projectID)
	var next_ord int64
	err := row.Scan(&next_ord)
	return next_ord, err
}

const nextResearchOrd = `-- name: NextResearchOrd :one
= ?;

SELECT CAST(COALESCE(MAX(ord), 0) + 1 AS INTEGER) AS next_ord FROM research WHERE project_id
`

func (q *Queries) NextResearchOrd(ctx context.Context, projectID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextResearchOrd, projectID)
	var next_ord int64
	err := row.Scan(&next_ord)
	return next_ord, err
}

const nextTaskOrd = `-- name: NextTaskOrd :one
= ?;

SELECT CAST(COALESCE(MAX(t.ord), 0) + 1 AS INTEGER) AS next_ord
FROM task t JOIN feature f ON f.id = t.feature_id
WHERE f.project_id
`

func (q *Queries) NextTaskOrd(ctx context.Context, projectID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextTaskOrd, projectID)
	var next_ord int64
	err := row.Scan(&next_ord)
	return next_ord, err
}

const nextUnknownOrd = `-- name: NextUnknownOrd :one
= ?;

SELECT CAST(COALESCE(MAX(u.ord), 0) + 1 AS INTEGER) AS next_ord
FROM unknown u JOIN feature f ON f.id = u.feature_id
WHERE f.project_id
`

func (q *Queries) NextUnknownOrd(ctx context.Context, projectID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextUnknownOrd, projectID)
	var next_ord int64
	err := row.Scan(&next_ord)
	return next_ord, err
}

const openUnknownFeatures = `-- name: OpenUnknownFeatures :many
i.name;

SELECT f.ord, f.name, CAST(count(*) AS INTEGER) AS n
FROM unknown u
JOIN feature f ON f.id = u.feature_id
WHERE f.project_id = ? AND u.status = 'open'
GROUP BY f.id
ORDER
`

type OpenUnknownFeaturesRow struct {
	Ord  sql.NullInt64
	Name string
	N    int64
}

func (q *Queries) OpenUnknownFeatures(ctx context.Context, projectID sql.NullInt64) ([]OpenUnknownFeaturesRow, error) {
	rows, err := q.db.QueryContext(ctx, openUnknownFeatures, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpenUnknownFeaturesRow{}
	for rows.Next() {
		var i OpenUnknownFeaturesRow
		if err := rows.Scan(&i.Ord, &i.Name, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectByPath = `-- name: ProjectByPath :one
?;

SELECT id FROM project WHERE path =
`

func (q *Queries) ProjectByPath(ctx context.Context, path string) (int64, error) {
	row := q.db.QueryRowContext(ctx, projectByPath, path)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const projectByURL = `-- name: ProjectByURL :one


SELECT id FROM project WHERE url =
`

// F8 sqlc query layer (V50): every domain SQL statement that previously lived as
// a hand-written string literal, as a named sqlc query. Generated into package db
// by `go tool sqlc generate`. Parameters use `?` (sqlc names them from the column)
// except where a value is reused or nullable, which use sqlc.arg/sqlc.narg.
// The only domain SQL that stays hand-written is backup.go's `.dump` (sqlite_master
// introspection + dynamic SELECT */INSERT over arbitrary tables) — structurally
// inexpressible in sqlc (table/columns unknown at codegen); the documented V50
// exception.
// ============================================================ project (resolve.go)
func (q *Queries) ProjectByURL(ctx context.Context, url sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, projectByURL, url)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const projectRowCount = `-- name: ProjectRowCount :one
= ?;


SELECT CAST(
	(SELECT count(*) FROM invariant WHERE invariant.project_id = ?)
	+ (SELECT count(*) FROM interface WHERE interface.project_id = ?)
	+ (SELECT count(*) FROM bug       WHERE bug.project_id = ?)
	+ (SELECT count(*) FROM research  WHERE research.project_id = ?)
	+ (SELECT count(*) FROM feature   WHERE feature.project_id = ?)
AS INTEG
`

type ProjectRowCountParams struct {
	ProjectID   sql.NullInt64
	ProjectID_2 sql.NullInt64
	ProjectID_3 sql.NullInt64
	ProjectID_4 sql.NullInt64
	ProjectID_5 sql.NullInt64
}

// ============================================================ seed/import wipe (import.go)
// Five positional params, all the same project id (sqlc names them ProjectID,
// ProjectID_2, …). Caller passes pid to each. Sum > 0 ⟺ the project has rows.
func (q *Queries) ProjectRowCount(ctx context.Context, arg ProjectRowCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, projectRowCount,
		arg.ProjectID,
		arg.ProjectID_2,
		arg.ProjectID_3,
		arg.ProjectID_4,
		arg.ProjectID_5,
	)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const researchByProject = `-- name: ResearchByProject :many
R BY id;

SELECT ord, topic, finding, src FROM research WHERE project_id = ? ORDE
`

type ResearchByProjectRow struct {
	Ord     sql.NullInt64
	Topic   string
	Finding string
	Src     string
}

func (q *Queries) ResearchByProject(ctx context.Context, projectID sql.NullInt64) ([]ResearchByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, researchByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResearchByProjectRow{}
	for rows.Next() {
		var i ResearchByProjectRow
		if err := rows.Scan(
			&i.Ord,
			&i.Topic,
			&i.Finding,
			&i.Src,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveUnknown = `-- name: ResolveUnknown :execrows
?);

UPDATE unknown SET status = 'resolved' WHERE unknown.ord = ? AND unknown.feature_id IN (SELECT feature.id FROM feature WHERE feature.project_id
`

type ResolveUnknownParams struct {
	Ord       sql.NullInt64
	ProjectID sql.NullInt64
}

func (q *Queries) ResolveUnknown(ctx context.Context, arg ResolveUnknownParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveUnknown, arg.Ord, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTaskStatus = `-- name: SetTaskStatus :execrows
= ?;

UPDATE task SET status = ? WHERE task.ord = ? AND task.feature_id IN (SELECT feature.id FROM feature WHERE feature.project_id
`

type SetTaskStatusParams struct {
	Status    string
	Ord       sql.NullInt64
	ProjectID sql.NullInt64
}

func (q *Queries) SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskStatus, arg.Status, arg.Ord, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const showBug = `-- name: ShowBug :one
ord = ?;

SELECT id, date, cause FROM bug WHERE project_id = ? AND
`

type ShowBugParams struct {
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
}

type ShowBugRow struct {
	ID    int64
	Date  string
	Cause string
}

func (q *Queries) ShowBug(ctx context.Context, arg ShowBugParams) (ShowBugRow, error) {
	row := q.db.QueryRowContext(ctx, showBug, arg.ProjectID, arg.Ord)
	var i ShowBugRow
	err := row.Scan(&i.ID, &i.Date, &i.Cause)
	return i, err
}

const showInterface = `-- name: ShowInterface :one
BY i.id;


SELECT kind, sig, status FROM interface WHERE project_id = ? AND
`

type ShowInterfaceParams struct {
	ProjectID sql.NullInt64
	Name      string
}

type ShowInterfaceRow struct {
	Kind   string
	Sig    string
	Status string
}

// ============================================================ reads: show (show.go)
func (q *Queries) ShowInterface(ctx context.Context, arg ShowInterfaceParams) (ShowInterfaceRow, error) {
	row := q.db.QueryRowContext(ctx, showInterface, arg.ProjectID, arg.Name)
	var i ShowInterfaceRow
	err := row.Scan(&i.Kind, &i.Sig, &i.Status)
	return i, err
}

const showInvariant = `-- name: ShowInvariant :one
ame = ?;

SELECT text FROM invariant WHERE project_id = ? AND
`

type ShowInvariantParams struct {
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
}

func (q *Queries) ShowInvariant(ctx context.Context, arg ShowInvariantParams) (string, error) {
	row := q.db.QueryRowContext(ctx, showInvariant, arg.ProjectID, arg.Ord)
	var text string
	err := row.Scan(&text)
	return text, err
}

const showResearch = `-- name: ShowResearch :one
ord = ?;

SELECT topic, finding, src FROM research WHERE project_id = ? AND
`

type ShowResearchParams struct {
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
}

type ShowResearchRow struct {
	Topic   string
	Finding string
	Src     string
}

func (q *Queries) ShowResearch(ctx context.Context, arg ShowResearchParams) (ShowResearchRow, error) {
	row := q.db.QueryRowContext(ctx, showResearch, arg.ProjectID, arg.Ord)
	var i ShowResearchRow
	err := row.Scan(&i.Topic, &i.Finding, &i.Src)
	return i, err
}

const showTask = `-- name: ShowTask :one
ord = ?;

SELECT t.id, t.status, t.text
FROM task t JOIN feature f ON f.id = t.feature_id
WHERE f.project_id = ? AND t
`

type ShowTaskParams struct {
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
}

type ShowTaskRow struct {
	ID     int64
	Status string
	Text   string
}

func (q *Queries) ShowTask(ctx context.Context, arg ShowTaskParams) (ShowTaskRow, error) {
	row := q.db.QueryRowContext(ctx, showTask, arg.ProjectID, arg.Ord)
	var i ShowTaskRow
	err := row.Scan(&i.ID, &i.Status, &i.Text)
	return i, err
}

const taskCiteIfaceNames = `-- name: TaskCiteIfaceNames :many
Y i.ord;

SELECT i.name FROM task_cites_iface j JOIN interface i ON i.id = j.iface_id WHERE j.task_id = ? ORDER
`

func (q *Queries) TaskCiteIfaceNames(ctx context.Context, taskID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, taskCiteIfaceNames, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskCiteInvOrds = `-- name: TaskCiteInvOrds :many
Y i.ord;

SELECT i.ord FROM task_cites_inv j JOIN invariant i ON i.id = j.inv_id WHERE j.task_id = ? ORDER
`

func (q *Queries) TaskCiteInvOrds(ctx context.Context, taskID int64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, taskCiteInvOrds, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var ord sql.NullInt64
		if err := rows.Scan(&ord); err != nil {
			return nil, err
		}
		items = append(items, ord)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskCitersOfInv = `-- name: TaskCitersOfInv :many
Y t.ord;

SELECT t.ord FROM task_cites_inv j JOIN task t ON t.id = j.task_id WHERE j.inv_id = ? ORDER
`

func (q *Queries) TaskCitersOfInv(ctx context.Context, invID int64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, taskCitersOfInv, invID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var ord sql.NullInt64
		if err := rows.Scan(&ord); err != nil {
			return nil, err
		}
		items = append(items, ord)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskOrdByID = `-- name: TaskOrdByID :one
= ?;

SELECT ord FROM task WHERE id
`

func (q *Queries) TaskOrdByID(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, taskOrdByID, id)
	var ord sql.NullInt64
	err := row.Scan(&ord)
	return ord, err
}

const taskStatusCounts = `-- name: TaskStatusCounts :many
Y b.ord;


SELECT status, CAST(count(*) AS INTEGER) AS n FROM task WHERE feature_id = ? GROUP B
`

type TaskStatusCountsRow struct {
	Status string
	N      int64
}

// ============================================================ reads: status / next (status.go, next.go, gate.go)
func (q *Queries) TaskStatusCounts(ctx context.Context, featureID int64) ([]TaskStatusCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, taskStatusCounts, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskStatusCountsRow{}
	for rows.Next() {
		var i TaskStatusCountsRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasksByFeature = `-- name: TasksByFeature :many
BY ord;

SELECT id, ord, status, text FROM task WHERE feature_id = ? ORDE
`

type TasksByFeatureRow struct {
	ID     int64
	Ord    sql.NullInt64
	Status string
	Text   string
}

func (q *Queries) TasksByFeature(ctx context.Context, featureID int64) ([]TasksByFeatureRow, error) {
	rows, err := q.db.QueryContext(ctx, tasksByFeature, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksByFeatureRow{}
	for rows.Next() {
		var i TasksByFeatureRow
		if err := rows.Scan(
			&i.ID,
			&i.Ord,
			&i.Status,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasksInProject = `-- name: TasksInProject :many
Y u.ord;


SELECT t.id, t.ord, t.status, t.text
FROM task t JOIN feature f ON f.id = t.feature_id
WHERE f.project_id = ? ORDER
`

type TasksInProjectRow struct {
	ID     int64
	Ord    sql.NullInt64
	Status string
	Text   string
}

// listTasksFiltered (V38/V53) picks one of these four by which filters are set;
// sqlc's SQLite engine rejects narg-style optional params, so the combinations
// are explicit. Feature existence is still resolved in Go (featurePK) before the
// by-feature variants run, so a missing feature errors rather than returns empty.
func (q *Queries) TasksInProject(ctx context.Context, projectID sql.NullInt64) ([]TasksInProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, tasksInProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksInProjectRow{}
	for rows.Next() {
		var i TasksInProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Ord,
			&i.Status,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasksInProjectByFeature = `-- name: TasksInProjectByFeature :many
Y t.ord;

SELECT t.id, t.ord, t.status, t.text
FROM task t JOIN feature f ON f.id = t.feature_id
WHERE f.project_id = ? AND t.feature_id = ? ORDER
`

type TasksInProjectByFeatureParams struct {
	ProjectID sql.NullInt64
	FeatureID int64
}

type TasksInProjectByFeatureRow struct {
	ID     int64
	Ord    sql.NullInt64
	Status string
	Text   string
}

func (q *Queries) TasksInProjectByFeature(ctx context.Context, arg TasksInProjectByFeatureParams) ([]TasksInProjectByFeatureRow, error) {
	rows, err := q.db.QueryContext(ctx, tasksInProjectByFeature, arg.ProjectID, arg.FeatureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksInProjectByFeatureRow{}
	for rows.Next() {
		var i TasksInProjectByFeatureRow
		if err := rows.Scan(
			&i.ID,
			&i.Ord,
			&i.Status,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasksInProjectByFeatureStatus = `-- name: TasksInProjectByFeatureStatus :many
Y t.ord;

SELECT t.id, t.ord, t.status, t.text
FROM task t JOIN feature f ON f.id = t.feature_id
WHERE f.project_id = ? AND t.feature_id = ? AND t.status = ? ORDER
`

type TasksInProjectByFeatureStatusParams struct {
	ProjectID sql.NullInt64
	FeatureID int64
	Status    string
}

type TasksInProjectByFeatureStatusRow struct {
	ID     int64
	Ord    sql.NullInt64
	Status string
	Text   string
}

func (q *Queries) TasksInProjectByFeatureStatus(ctx context.Context, arg TasksInProjectByFeatureStatusParams) ([]TasksInProjectByFeatureStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, tasksInProjectByFeatureStatus, arg.ProjectID, arg.FeatureID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksInProjectByFeatureStatusRow{}
	for rows.Next() {
		var i TasksInProjectByFeatureStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Ord,
			&i.Status,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tasksInProjectByStatus = `-- name: TasksInProjectByStatus :many
Y t.ord;

SELECT t.id, t.ord, t.status, t.text
FROM task t JOIN feature f ON f.id = t.feature_id
WHERE f.project_id = ? AND t.status = ? ORDER
`

type TasksInProjectByStatusParams struct {
	ProjectID sql.NullInt64
	Status    string
}

type TasksInProjectByStatusRow struct {
	ID     int64
	Ord    sql.NullInt64
	Status string
	Text   string
}

func (q *Queries) TasksInProjectByStatus(ctx context.Context, arg TasksInProjectByStatusParams) ([]TasksInProjectByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, tasksInProjectByStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksInProjectByStatusRow{}
	for rows.Next() {
		var i TasksInProjectByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Ord,
			&i.Status,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unknownsByProject = `-- name: UnknownsByProject :many
R BY id;

SELECT u.ord, u.status, u.text
FROM unknown u JOIN feature f ON f.id = u.feature_id
WHERE f.project_id = ? ORDER
`

type UnknownsByProjectRow struct {
	Ord    sql.NullInt64
	Status string
	Text   string
}

func (q *Queries) UnknownsByProject(ctx context.Context, projectID sql.NullInt64) ([]UnknownsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, unknownsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnknownsByProjectRow{}
	for rows.Next() {
		var i UnknownsByProjectRow
		if err := rows.Scan(&i.Ord, &i.Status, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGate = `-- name: UpsertGate :exec
ING;

INSERT INTO gate(feature_id, verdict, note, recorded_at) VALUES(?, ?, ?, ?)
ON CONFLICT(feature_id) DO UPDATE SET
	verdict = excluded.verdict, note = excluded.note, recorded_at = excluded.recorde
`

type UpsertGateParams struct {
	FeatureID  int64
	Verdict    string
	Note       sql.NullString
	RecordedAt string
}

func (q *Queries) UpsertGate(ctx context.Context, arg UpsertGateParams) error {
	_, err := q.db.ExecContext(ctx, upsertGate,
		arg.FeatureID,
		arg.Verdict,
		arg.Note,
		arg.RecordedAt,
	)
	return err
}

const wipeFeature = `-- name: WipeFeature :execrows
?);

DELETE FROM feature WHERE project_id = ? AND ord
`

type WipeFeatureParams struct {
	ProjectID sql.NullInt64
	Ord       sql.NullInt64
}

func (q *Queries) WipeFeature(ctx context.Context, arg WipeFeatureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, wipeFeature, arg.ProjectID, arg.Ord)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
