// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Bug struct {
	ID        int64
	ProjectID int64
	Ord       int64
	Date      string
	Cause     string
}

type BugFix struct {
	BugID int64
	InvID int64
}

type CommandUsage struct {
	ProjectID int64
	Command   string
	OkCount   int64
	FailCount int64
	LastSeen  string
}

type Constraint struct {
	ID        int64
	FeatureID int64
	Text      string
}

type Feature struct {
	ID        int64
	ProjectID int64
	Ord       int64
	Name      string
}

type Gate struct {
	ID         int64
	FeatureID  int64
	Verdict    string
	Note       sql.NullString
	RecordedAt string
}

type Goal struct {
	ID        int64
	FeatureID int64
	Text      string
}

type Interface struct {
	ID        int64
	ProjectID int64
	Kind      string
	Name      string
	Sig       string
	Status    string
}

type Invariant struct {
	ID        int64
	ProjectID int64
	Ord       int64
	Text      string
}

type Project struct {
	ID   int64
	Url  sql.NullString
	Path string
}

type Research struct {
	ID        int64
	ProjectID int64
	Ord       int64
	Topic     string
	Finding   string
	Src       string
}

type Task struct {
	ID        int64
	FeatureID int64
	Ord       int64
	Text      string
	Status    string
}

type TaskCitesIface struct {
	TaskID  int64
	IfaceID int64
}

type TaskCitesInv struct {
	TaskID int64
	InvID  int64
}

type Test struct {
	ID          int64
	InvariantID int64
	Name        string
}

type Unknown struct {
	ID        int64
	FeatureID int64
	Ord       int64
	Text      string
	Status    string
}
